version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/hydra_mdm
      - JWT_SECRET=your-secret-key
      - PORT=3000
      - LOG_LEVEL=info
      - CORS_ORIGIN=http://localhost:3001
    depends_on:
      - db
    volumes:
      - ./logs:/app/logs

  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=hydra_mdm
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 